export default {
  "[data-theme=light]": {
    primary: "#570df8",
    "primary-content": "#ffffff",
    secondary: "#f000b8",
    "secondary-content": "#ffffff",
    accent: "#37cdbe",
    "accent-content": "#ffffff",
    neutral: "#3d4451",
    "neutral-content": "#ffffff",
    "base-100": "#ffffff",
    "base-200": "#f9fafb",
    "base-300": "#d1d5db",
    "base-content": "#1f2937",
  },
  "[data-theme=dark]": {
    primary: "#661AE6",
    "primary-content": "#ffffff",
    secondary: "#D926AA",
    "secondary-content": "#ffffff",
    accent: "#1FB2A5",
    "accent-content": "#ffffff",
    neutral: "#191D24",
    "neutral-focus": "#111318",
    "neutral-content": "#A6ADBB",
    "base-100": "#2A303C",
    "base-200": "#242933",
    "base-300": "#20252E",
    "base-content": "#A6ADBB",
  },
};
