name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # set this token manually
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0" # pulls all history and tags for Lerna to detect what packages changed.
          token: ${{ secrets.GITHUB_TOKEN }} # this token is available by default

      # setup .npmrc using NODE_AUTH_TOKEN
      - name: Setup .npmrc file for publish
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Configure Git User
        run: |
          git config --global user.email "lerna-ci@pankow.com"
          git config --global user.name "lerna-ci@$GITHUB_ACTOR"

      - name: Check if able to publish changes
        run: npm whoami # will throw and exit if npm is not ready to publish

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Publish
        run: lerna publish --force-publish --no-verify-access # the flag is needed if NPM_TOKEN is an Automation Token
